// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6RMlHyq3QKhYxdsZITddOkvfQNMcETI',
    appId: '1:54110600029:web:479d213e11420c0b5946b4',
    messagingSenderId: '54110600029',
    projectId: 'eoullim-7e5fb',
    authDomain: 'eoullim-7e5fb.firebaseapp.com',
    databaseURL: 'https://eoullim-7e5fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eoullim-7e5fb.appspot.com',
    measurementId: 'G-2957PMMRBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdI7sATkgwTqiPxtuGJc1q9fbo16SHO5M',
    appId: '1:54110600029:android:cd6e73ec1d8e5b7f5946b4',
    messagingSenderId: '54110600029',
    projectId: 'eoullim-7e5fb',
    databaseURL: 'https://eoullim-7e5fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eoullim-7e5fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQeX5f24uYyJLfbEjwwr_u4i5iynxLVI',
    appId: '1:54110600029:ios:db925ce88dc3e3515946b4',
    messagingSenderId: '54110600029',
    projectId: 'eoullim-7e5fb',
    databaseURL: 'https://eoullim-7e5fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eoullim-7e5fb.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQeX5f24uYyJLfbEjwwr_u4i5iynxLVI',
    appId: '1:54110600029:ios:31170812468d94525946b4',
    messagingSenderId: '54110600029',
    projectId: 'eoullim-7e5fb',
    databaseURL: 'https://eoullim-7e5fb-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eoullim-7e5fb.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
